### ISSUE TITLE
Am I doing sth wrong?

### ISSUE THREAD

**Issue by J3fflo** [zesterer/teloren#15]
Aight. soo, basically Ive got no ideea what Im doing. I somehow managed to build it and run it, but when i get to selecting a character this happens.. 
```
thread 'main' panicked at 'Failed to create client instance: StreamErr(Deserialize(Custom("invalid value: integer `5`, expected variant index 0 <= i < 5")))', src/main.rs:117:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I dont have much experience with rust, so this might all just be my fault. (most probably)

**Comment by cpetig** [comment]
I just undusted the code, today it worked fine against the standard server. I suspect that you just had bad luck with an outdated client library.

**Comment by J3fflo** [comment]
now it gives out this error:
`thread 'main' panicked at 'assertion failed: client.tick(comp::ControllerInputs::default(), clock.dt(), |_| ()).is_ok()', src/main.rs:138:9`
after connecting to the srv

**Comment by cpetig** [comment]
With Syniis latest changes (3d ago) it will prefer the weekly branch, so after an cargo update the resulting binary should work - for today https://github.com/zesterer/teloren/pull/20 will give you the right set of dependencies.

Please note that due to a roughly weekly update of the server you likely need to update dependencies (cargo update) for teloren before using it on the default server.

**Comment by cpetig** [comment]
@J3fflo would you agree to close this ticket?
